### ISSUE TITLE
Add deployment checklist for Zango project in docs

### ISSUE THREAD

**Issue by kc-diabeat** [Healthlane-Technologies/Zango#251]
**Description:**

As part of improving the deployment process for Zango project, we need to create a comprehensive deployment checklist in Zango docs. This checklist will help ensure that all necessary steps are taken and best practices are followed during the deployment of Zango project. 

**Checklist Items:**

1. **Environment Variables:**
   - [ ] Updating the correct 'env_type'
   - [ ] Secret Key - Process for generating and updating a secure secret.
   - [ ] INTERNAL_IPS - Update internal IPs if access to App Panel needs to be restricted
   - [ ] Session Timeout
   - [ ] Auto Lockout 
   - [ ] Media Storage
   - [ ] Static Storage

2. **Hardening:**
   - [ ] Deactivate/ Delete any default platform users

**Comment by kc-diabeat** [comment]
@shahharsh176 Pls include additional points that might be missed
